version: '3'
services:
  git:
    image: gitlab/gitlab-ee:latest
    hostname: 'gitlab.example.com'
    ports:
      - '8090:80'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    networks:
      - net
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = 'yourpassword'
        gitlab_rails['require_admin_approval_after_user_signup'] = false
    

networks:
  net: